### CREATE OFFER
POST localhost:3000/api/offers HTTP/1.1
Content-Type: application/json

{
  "category": [
    "Книги"
  ],
  "description": "Продаю с болью в сердце... Бонусом отдам все аксессуары. Если найдёте дешевле — сброшу цену. Это настоящая находка для коллекционера!",
  "picture": "item01.jpg",
  "title": "Куплю породистого кота",
  "type": "sale",
  "sum": 71932
}

### UPDATE OFFER
PUT localhost:3000/api/offers/ HTTP/1.1
Content-Type: application/json

{
  "id": "",
  "category": [
    "CNJKS"
  ],
  "description": "Продаю с болью в сердце... Бонусом отдам все аксессуары. Если найдёте дешевле — сброшу цену. Это настоящая находка для коллекционера!",
  "picture": "item01.jpg",
  "title": "Куплю породистого кота",
  "type": "sale",
  "sum": 71932
}

### DELETE OFFER
DELETE localhost:3000/api/offers/cU37M5FxshXpY-0tyg5hO HTTP/1.1
Content-Type: application/json

### DELETE COMMENT
DELETE http://localhost:3000/api/offers/sUMRpEQUz4W-GYwuedYPs/comments/jruGg9vOqYedhlV2y2gU3 HTTP/1.1
Content-Type: application/json

### PUT COMENT
PUT localhost:3000/api/offers/7FVoVbTBxLzLhCKw-Ke85/comments/ HTTP/1.1
Content-Type: application/json

{
  "text": "TEXT"
}
